---
- name: create stack
  cloudformation:
    stack_name: "{{ stack_name }}"
    state: present
    region: "{{ aws_region }}"
    template: "{{ role_path }}/files/cloudformation.yml"
    template_parameters:
      VpcName: "{{ vpc_name }}"
      VpcCidrBlock: "{{ vpc_cidr_block }}"
      SubnetCidrBlock: "{{ subnet_cidr_block }}"
      SubnetZone: "{{ subnet_zone }}"
      KeyPairName: "{{ key_pair_name }}"
      InstanceType: "{{ instance_type }}"
      AmiId: "{{ ami_id }}"
      InstanceName: "{{ instance_name }}"
      HostedZone: "{{ hosted_zone }}"
  
- name: retrieve stack facts
  cloudformation_facts:
    stack_name: "{{ stack_name }}"
    region: "{{ aws_region }}"
  register: stack_facts

- set_fact:
    public_ip: "{{ stack_facts.ansible_facts.cloudformation[stack_name].stack_outputs.PublicIp }}"

- name: copy pem file
  copy:
    src: "{{ key_pair_name }}.pem"
    dest: "{{ target_working_dir }}/{{ key_pair_name }}.pem"
    mode: 0400

- name: add web server host
  add_host:
    hostname: instance
    ansible_ssh_host: "{{ public_ip }}"
    ansible_ssh_user: ubuntu
    ansible_ssh_private_key_file: "{{ target_working_dir }}/{{ key_pair_name }}.pem"