Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
  end

  config.vm.box = "ubuntu/xenial64"
  config.vm.network :forwarded_port, guest: 80, host: 80
  config.vm.provision :shell, path: "bootstrap.sh", env: {
    GITHUB_OAUTH_KEY:ENV['GITHUB_OAUTH_KEY'], 
    GITHUB_OAUTH_SECRET:ENV['GITHUB_OAUTH_SECRET'],
    NEXTZEN_KEY:ENV['NEXTZEN_KEY']
  }
end