version: '3'
services:
  wof-indexer:
    image: lumberbarons/wof-indexer:latest
    container_name: wof-indexer
    volumes:
      - wofdata:/usr/local/data
    environment:
      - ELASTICSEARCH_HOST=wof-elasticsearch
      - WOFDATA_GITHUB_URL=${WOFDATA_GITHUB_URL}
    networks:
      - wof-network
    depends_on:
      - wof-elasticsearch
  wof-data:
    image: lumberbarons/wof-data:latest
    container_name: wof-data
    volumes:
      - wofdata:/usr/local/data
    networks:
      - wof-network
  wof-spelunker:
    image: lumberbarons/wof-spelunker:latest
    container_name: wof-spelunker
    environment:
      - NEXTZEN_KEY=${NEXTZEN_KEY}
    networks:
      - wof-network
  wof-proxy:
    image: lumberbarons/wof-proxy:latest
    container_name: wof-proxy
    ports:
      - 80:80
    networks:
      - wof-network
    depends_on:
      - wof-spelunker
      - wof-data
  wof-elasticsearch:
    image: elasticsearch:2.4.6
    container_name: wof-elasticsearch
    environment:
      - cluster.name=whosonfirst
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - wof-network

volumes:
  wofdata:
  esdata:
networks:
  wof-network: