server:
  port: 80
  compression:
    enabled: true
    mime-types: application/json
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
jwt:
  header: Authorization
  expiration: 604800