server:
  port: 8000
  compression:
    enabled: true
    mime-types: application/json
spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  datasource:
    url: jdbc:mysql://localhost:3306/wof_admin?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: secret
jwt:
  secret: secret
  header: Authorization
  expiration: 604800
wof:
  elasticsearch:
    host: 127.0.0.1
    port: 9200
    spelunker:
      index: spelunker_20181215
      alias: spelunker