version: '3'
services:
  elasticsearch:
    image: elasticsearch:2.4.6
    container_name: elasticsearch
    environment:
      - cluster.name=whosonfirst
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/es:/usr/share/elasticsearch/data
    ports:
      - 9200:9200